# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_create-data-block.ipynb.

# %% auto 0
__all__ = ['pkl_dir', 'pkl_file', 'data_dir', 'block']

# %% ../nbs/06_create-data-block.ipynb 2
import os,torch, torch.multiprocessing as mp, pickle, numpy as np
from xcai.basics import *

# %% ../nbs/06_create-data-block.ipynb 4
pkl_dir = '/home/scai/phd/aiz218323/scratch/datasets/'
pkl_file = f'{pkl_dir}/processed/wikiseealsotitles_data-lnk_distilbert-base-uncased_xcs.pkl'

data_dir = '/home/scai/phd/aiz218323/Projects/XC_NLG/data'

block = XCBlock.from_cfg(data_dir, 'data_lnk', transform_type='xcs', tokenizer='distilbert-base-uncased', 
                         sampling_features=[('lbl2data',4), ('lnk2data',3)], oversample=True)

with open(pkl_file, 'wb') as file: pickle.dump(block, file)

# %% ../nbs/06_create-data-block.ipynb 5
pkl_dir = '/home/scai/phd/aiz218323/scratch/datasets/'
pkl_file = f'{pkl_dir}/processed/wikititles_data-lnk_distilbert-base-uncased_xcs.pkl'

data_dir = '/home/scai/phd/aiz218323/Projects/XC_NLG/data'

block = XCBlock.from_cfg(data_dir, 'data_lnk', dset='wikititles', transform_type='xcs', tokenizer='distilbert-base-uncased', 
                         sampling_features=[('lbl2data',4), ('lnk2data',3)], oversample=True)

with open(pkl_file, 'wb') as file: pickle.dump(block, file)
