# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/medic',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/medic',
                'lib_path': 'medic'},
  'syms': {'medic.core': {'medic.core.foo': ('core.html#foo', 'medic/core.py')}}}
